### ISSUE TITLE
[Docker] Possibility to have this run in a Docker

### ISSUE THREAD

**Issue by fly-man-** [vladmandic/pigallery#10]
Is there any possibility to have this to run as a Docker ?

**Comment by vladmandic** [comment]
sure, but at the moment there is no pre-made docker config - thats a good request for enhancement, i'll add it next week.

**Comment by vladmandic** [comment]
i've though about what value can be added by creating custom docker configuration, but at the end its just a default one - pigallery works fine in a docker and how to do it is how you dockerize any nodejs application, nothing really specific
