### ISSUE TITLE
It hangs on npm start

### ISSUE THREAD

**Issue by ilearnio** [vladmandic/pigallery#11]
It hangs for me on this step. I waited for a few hours then quit the process.

![image](https://user-images.githubusercontent.com/14331216/135984556-35b8c4a3-d580-4fdb-9ede-d57f1045ce89.png)

Node v14.16.0
NPM v7.24.0

**Comment by vladmandic** [comment]
where is the hang? i see the server is ready & listening for requests  
what happens when you navigate to <https://localhost:10011>?

**Comment by ilearnio** [comment]
Sorry, my bad. Was checking wrong port
