### ISSUE TITLE
Add exif attrbutes to the image files?

### ISSUE THREAD

**Issue by krixoko** [vladmandic/pigallery#16]
Is it possible to add  EXIF attrbutes to the image files?

**Comment by vladmandic** [comment]
you mean manually edit them? not currently, but thats not a bad idea (if that is the ask).

**Comment by krixoko** [comment]
yeah, select one or all on the page, then add the tags into the image file itself, so when exporting this images to external source, the tags are still in the image.

**Comment by vladmandic** [comment]
currently `pigallery` does not modify files in any way and i'm not sure i'd want to start doing that. but i'll keep it in mind for the next major release.
