### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by alphaleadership** [vladmandic/pigallery#17]
add a admin command line interface to process image

**Comment by vladmandic** [comment]
i need to refactor processing to move it to server side to make that viable.
when i first wrote this project, tensorflow in nodejs was pretty buggy, so i opted to use browser-side for processing.
anyhow, good suggestion, but i'm closing it for now until i have time to refactor the repo in a larger way.

**Comment by alphaleadership** [comment]
you dont dont time
