### ISSUE TITLE
Multiple errors - dependency issues / installation / missing

### ISSUE THREAD

**Issue by lyoneel** [vladmandic/pigallery#18]
Hi, I was trying to install pigallery, and I had few problems.

The current error is at the end, but I documented here the process because I did solve few other errors that may be useful for someone else.

I'm using NixOS 23.05 stable with Node v18.16.1.

I followed the installation instructions (https://github.com/vladmandic/pigallery), then I did:

`npm run`

I got:

`Error: Cannot find module '@vladmandic/pilogger'`

I solve using yarn:

`yarn install`

When I did a run the server again I got the following:

```
ERROR] Could not resolve "@vladmandic/human/dist/human.esm"

    client/video/video.ts:9:22:
      9 │ import { Human } from '@vladmandic/human/dist/human.esm';
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./dist/human.esm" is not exported by package "@vladmandic/human":

```

At this point is tricky, server starts but index.css and index.js are missing.
I read what you said here: https://github.com/vladmandic/human/issues/209

And I did these two:
`npm i @types/vladmandic__human`
`npm install git+https://github.com/vladmandic/human`

and I got from both:
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:src/tfjs-backend-cpu
```

So I try those two with Yarn:

`yarn add @types/vladmandic_human`

Didn't work, but this did the tick:

`yarn add  @types/vladmandic/human`

````
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fvladmandic/human: Request\"https://registry.yarnpkg.com/@types%2fvladmandic/human\" returned a 405".
````

Again that didn't work, I did this instead and finally it worked (dependency):

`yarn add --dev git+https://github.com/vladmandic/human`

```
yarn add v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Rebuilding all packages...
success Saved lockfile.
success Saved 9 new dependencies.
info Direct dependencies
└─ @vladmandic/human@3.0.7
info All dependencies
├─ @tensorflow/tfjs-backend-cpu@0.0.0
├─ @tensorflow/tfjs-backend-wasm@0.0.0
├─ @tensorflow/tfjs-backend-webgl@0.0.0
├─ @tensorflow/tfjs-backend-webgpu@0.0.0
├─ @tensorflow/tfjs-converter@0.0.0
├─ @tensorflow/tfjs-core@0.0.0
├─ @tensorflow/tfjs-data@0.0.0
├─ @tensorflow/tfjs-layers@0.0.0
└─ @vladmandic/human@3.0.7
```

It did install correctly, but the import after a `npm run` is still failing:
```
ERROR] Could not resolve "@vladmandic/human/dist/human.esm"

    client/video/runHuman.ts:1:22:
      1 │ import { Human } from '@vladmandic/human/dist/human.esm';
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./dist/human.esm" is not exported by package "@vladmandic/human":
```

I just run out of ideas, (and some patience) any help is appreciated.

**Comment by vladmandic** [comment]
its been a long time since last update to this app, i'll need to bring it up to speed.
but for 99% of issues, simply using `import { Human } from '@vladmandic/human';` should just work.

**Comment by KjeldsenDK** [comment]
I was about to try this out, just getting through the official installation would be a challenge for me, this post saved me from hours of wasted time, thanks :)
